2372 in ssdc fix queue names now to be consistent
ONSdigital/ssdc-rm-toolbox pull request #5
Opened 2021-06-24 10:57 UTC by LukeLoze1

queue renaming

2021-06-25 06:03 UTC, NickGrantONS commented on Dockerfile
> +ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
case looks wrong

2021-06-25 06:04 UTC, NickGrantONS commented on Dockerfile
> +ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```suggestion
ENV RABBITMQ_QUEUE supportTool.caseProcessor.sample
```
```suggestion
ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```

2021-06-25 06:04 UTC, NickGrantONS commented on Dockerfile
> +ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```suggestion
ENV RABBITMQ_QUEUE supportTool.caseProcessor.sample
```
```suggestion
ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```

2021-06-25 06:05 UTC, NickGrantONS commented on Dockerfile
> +ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```suggestion
ENV RABBITMQ_QUEUE supportTool.caseProcessor.sample
```
```suggestion
ENV RABBITMQ_QUEUE SampleLoader.Case.Sample
```

2021-06-25 06:05 UTC, NickGrantONS commented on sample_loader/rabbit_context.py
> +        self.queue_name = kwargs.get('queue_name') or os.getenv('RABBITMQ_QUEUE', 'SampleLoader.Case.Sample')
```suggestion
        self.queue_name = kwargs.get('queue_name') or os.getenv('RABBITMQ_QUEUE', 'supportTool.caseProcessor.sample')
```
```suggestion
        self.queue_name = kwargs.get('queue_name') or os.getenv('RABBITMQ_QUEUE', 'SampleLoader.Case.Sample')
```

2021-06-25 06:05 UTC, NickGrantONS requested changes
Qwrong.com

2021-06-28 13:18 UTC, NickGrantONS approved these changes
Builds and ATs passing 👍

2021-06-28 13:49 UTC, AdamHawtin approved these changes

2021-06-28 14:09 UTC, merged